# Generated by Django 4.0.4 on 2022-06-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailapp', '0002_alter_studentmodel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentmodel',
            table='studentmodel',
        ),
    ]
