# Generated by Django 4.0.4 on 2022-06-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailapp', '0004_deptmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptmodel',
            old_name='name',
            new_name='deptname',
        ),
    ]
