# Generated by Django 4.0.4 on 2022-06-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailapp', '0005_rename_name_deptmodel_deptname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptmodel',
            old_name='faculty_name',
            new_name='facultyname',
        ),
    ]
