# Generated by Django 4.0.4 on 2022-06-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailapp', '0006_rename_faculty_name_deptmodel_facultyname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deptmodel',
        ),
    ]
